### ISSUE TITLE
Differing levels

### ISSUE THREAD

**Issue by jmfurlott** [timdp/winston-aws-cloudwatch#28]
I would like to create a `logStreamName` for errors and another for `info` or `debug` etc so that I can have my error'ed logs partitioned in CloudWatch (and so ultimately I can set an Alarm to notify me on any Errors).  Currently in the base transports you can specify level, but there doesn't seem to be an option here for CloudWatch.

Is it possible to do this using this transporter?

**Comment by timdp** [comment]
No, unfortunately not. You should be able to pass two instances of the transport to winston though. I'm not sure if winston is able to send _just_ one level rather than everything above that level, so you might also need to use custom log levels. 

If you find a way, feel free to document it here. A PR would of course also be appreciated. :smile:
