### ISSUE TITLE
Program doesn't terminate

### ISSUE THREAD

**Issue by iter-io** [timdp/winston-aws-cloudwatch#50]
Hello.  We have been using our own fork cloudwatch transport created by lazywithclass.  We tried to move over to your version.  However, we need our program to terminate at the end:

https://github.com/lazywithclass/winston-cloudwatch/issues/41

Do you have any plans to add a feature like this scripts that do not run persistently?  In our version of the transport we use setTimeout instead of setInterval to get the desired behavior.

**Comment by timdp** [comment]
winston-aws-cloudwatch doesn't use `setInterval` or `setTimeout`. Instead, it throttles submissions to CloudWatch using [Bottleneck](https://npmjs.com/package/bottleneck). It shouldn't schedule anything after the last log message has been submitted; otherwise, the tests also wouldn't terminate.

Hence, if your program doesn't exit, I'm afraid you may be experiencing some other issue.

You might be able to debug this by logging the result of `process._getActiveHandles()` and/or `process._getActiveRequests()` when you expect your process to be ready to terminate. These things are hard to hunt down though.

**Comment by iter-io** [comment]
We updated several libraries at once and a different one was causing the the program not to exit.  Thank you for your prompt response.  I have been reading the source code of your module and it looks solid.

**Comment by timdp** [comment]
Glad you like it! :+1:
